version: '3.6'
services:
  postgres:
    image: postgres:11.3-alpine
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  nginx:
    image: nginx:1.15.12-alpine
    ports:
    - "3001:80"
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./resources/public:/var/www/html
    depends_on:
    - "graphql-engine"
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.2.cli-migrations
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    volumes:
    - ./hasura/migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: "/srv/console-assets"
volumes:
  db_data:
