version: '3.6'
services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
    - db_data:/var/lib/postgresql/data
  nginx:
    image: nginx:1.17.10
    ports:
    - "3001:80"
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./resources/public:/var/www/html
    depends_on:
    - "graphql-engine"
  graphql-engine:
    image: hasura/graphql-engine:v1.2.0-beta.4.cli-migrations
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    volumes:
    - ./hasura/migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: "/srv/console-assets"
volumes:
  db_data:
